### ISSUE TITLE
Instructions on how to build and run tests

### ISSUE THREAD

**Issue by keilw** [Tenkiv/Physikal#2]
I tried to build the project and run unit tests, but it does not work out of the box.
I get an error when running
```
>gradlew build
DEBUG BUILD
complete-units
DEBUG BUILD
core
DEBUG BUILD
si-units
:compileKotlin NO-SOURCE
:compileJava NO-SOURCE
:copyMainKotlinClasses UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestKotlin NO-SOURCE
:compileTestJava NO-SOURCE
:copyTestKotlinClasses UP-TO-DATE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test NO-SOURCE
:check UP-TO-DATE
:build UP-TO-DATE
:core:compileKotlin UP-TO-DATE
:core:compileJava NO-SOURCE
:core:copyMainKotlinClasses UP-TO-DATE
:core:processResources NO-SOURCE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:si-units:compileKotlin UP-TO-DATE
:si-units:compileJava NO-SOURCE
:si-units:copyMainKotlinClasses UP-TO-DATE
:si-units:processResources NO-SOURCE
:si-units:classes UP-TO-DATE
:si-units:jar UP-TO-DATE
:complete-units:compileKotlin UP-TO-DATE
:complete-units:compileJava NO-SOURCE
:complete-units:copyMainKotlinClasses UP-TO-DATE
:complete-units:processResources NO-SOURCE
:complete-units:classes UP-TO-DATE
:complete-units:jar UP-TO-DATE
:core:javadoc NO-SOURCE
:si-units:javadoc NO-SOURCE
:complete-units:javadoc NO-SOURCE
:complete-units:javadocJar UP-TO-DATE
:complete-units:sourcesJar UP-TO-DATE
:complete-units:signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Error while evaluating property 'signatory' of task ':complete-units:signArchives'
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
on the command line.

Importing it into IntelliJ there seems to be a way to build, but none of the tests can be executed.
The `test` goal of Gradle does not find any tests, so either it requires a different type of test runner (for Kotlin) or something else is missing.

Could you please document e.g. in the README some basic steps on how to build it and run tests.

Thanks.

**Comment by ejberry** [comment]
Issue resulting in failed builds stemming from missing local property has been resolved.

We were debating between using Spek and KotlinTest up until this point for our testing framework, but after some discussion we've settled on KotlinTest which has a cleaner DSL. The most recent commit should build and test normally.

**Comment by keilw** [comment]
Thanks, will give it another try. Pity you did not propose your  Kotlin-based Clean Energy solutions to JavaOne, did you? They could have been a great topic, also for the "Community Day" on the Sunday before JavaOne (CFP for that closed now, too) If you are not too busy we'd be happy to see you e.g. at the Public JCP EC Meeting (which usually is on Community Sunday, so it'll be October 1) or a JCP Meet and Greet which normally happens on Wed (Oct 4) where those interested in what the JCP is about can meet the PMO and Spec Leads or EG members. We are usually around. And Kotlin backing company JetBrains is also in the EC, so they could be there and happy to talk to you about how you use it.

**Comment by zjuhasz** [comment]
We didn't propose any of our work to JavaOne as we didn't really understand what's involved in doing so or what they're looking for. We'd definitely like to meet with you and other JCP EC members, thanks for the invitation! Does attending the Public JCP EC meeting require a JavaOne ticket? We talked about attending the conference a few months ago but we had trouble justifying the cost.

**Comment by keilw** [comment]
There's a JCP EC call today, I'll ask Heather if I can, there should be an agenda item to discuss JavaOne efforts. The "Meet the JCP" event so far was always in a Hilton suite, so no ticket necessary. I cannot say for sure, if the Community day or public EC Meeting is accessible without a JavaOne ticket, but it should be IMO to really be "public" ;-)

**Comment by keilw** [comment]
Unfortunately the "Meet the JCP" event had fewer attendees the past few years, so it was not approved by Oracle any more. The Public EC Meeting requires a JavaOne pass, but I trust there will be an opportunity to meet @otaviojava, @leomrlima or @trishagee (who represents JetBrains) to talk about how @Tenkiv uses Kotlin and JSR 363 to help the environment.
