### ISSUE TITLE
Change artifactId from core to physikal-core

### ISSUE THREAD

**Issue by linux-china** [Tenkiv/Physikal#4]
Now maven dependency as following, and I think core is very common word and may conflict with other dependency and not easy to understand in WEB-INF/lib. 
```
<dependency>
                <groupId>org.tenkiv.physikal</groupId>
                <artifactId>core</artifactId>
                <version>1.0.0.0</version>
            </dependency>
```
and I think the following one will be better

```
<dependency>
                <groupId>org.tenkiv.physikal</groupId>
                <artifactId>physikal-core</artifactId>
                <version>1.0.0.0</version>
            </dependency>
```

**Comment by ejberry** [comment]
The pattern we've chosen to follow with our naming scheme differentiates the projects in the groupId and subdivides the project in the artifactId. While this is subjective and less common, [were not the only ones to have done so.](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22core%22) Doing this makes the artifacts less verbose and cleaner in Gradle, which is the build system we use.
